# Generated from Omarchy colors.toml — do not edit
# Regenerated by: omarchy theme set / omarchy theme refresh

[theme]
name = "terminal"

[theme.custom]
accent = "{{ accent }}"
# The active tab is drawn as panel_bg text on an accent background, so panel_bg
# has to be dark for it to read - same as tmux status-left's fg={{ color0 }}
panel_bg = "{{ color0 }}"
